In [1]:
import torch

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
BLOCK_SIZE = 5
BATCH_SIZE = 4

In [2]:
with open("data/wizard_of_oz.txt", "r", encoding="utf-8") as f:
    text = f.read()
chars = sorted(set(text))
print(chars)
print(len(chars))

['\n', ' ', '!', '"', '&', "'", '(', ')', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '\ufeff']
76


In [13]:
string_to_int = {ch:i for i,ch in enumerate(chars)}
int_to_string = {i:ch for i,ch in enumerate(chars)}
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda s: [int_to_string[c] for c in s]

data = torch.tensor(encode(text), dtype=torch.long)
data[:100]

tensor([75, 43, 63,  1, 36, 73,  1, 41, 53, 49, 52, 53, 66, 67,  0,  0,  0, 32,
        68,  5, 67,  1, 62, 63,  1, 69, 67, 53, 22,  1, 62, 63,  1, 69, 67, 53,
         1, 49, 68,  1, 49, 60, 60, 10,  1,  1, 43, 56, 53,  1, 51, 56, 57, 60,
        52, 66, 53, 62,  1, 71, 63, 62,  5, 68,  1, 60, 53, 68,  1, 61, 53,  1,
        67, 68, 63, 64,  1, 68, 53, 60, 60, 57, 62, 55,  0, 68, 49, 60, 53, 67,
         1, 63, 54,  1, 68, 56, 53,  1, 35, 49])

In [17]:
train_test_split = 0.8
split_index = int(train_test_split*len(data))
train_data = data[:split_index]
test_data = data[split_index:]

In [23]:
x = train_data[:BLOCK_SIZE]
y = train_data[1:BLOCK_SIZE+1]

for t in range(BLOCK_SIZE):
    context = x[:t+1]
    target = y[t]
    print(f"{context} -> {target}")

tensor([64]) -> 66
tensor([64, 66]) -> 63
tensor([64, 66, 63]) -> 70
tensor([64, 66, 63, 70]) -> 63
tensor([64, 66, 63, 70, 63]) -> 59
tensor([64, 66, 63, 70, 63, 59]) -> 53
tensor([64, 66, 63, 70, 63, 59, 53]) -> 52
tensor([64, 66, 63, 70, 63, 59, 53, 52]) -> 10
