In [1]:
import torch

In [11]:
# Get a tensor filled with random ints
randint = torch.randint(-100, 100, (6,))
randint

tensor([ 13, -60, -30, -69,  -2,  -4])

In [14]:
# Create a tensor
tensor = torch.tensor([[0.1, 1.2], [0.1, 1.2], [0.1, 1.2]])
tensor

tensor([[0.1000, 1.2000],
        [0.1000, 1.2000],
        [0.1000, 1.2000]])

In [15]:
# Get a tensor filled with zeros
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [16]:
# Get a tensor filled with ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
# Get a tensor with uninitialised data
input = torch.empty(2, 3)
input

tensor([[8.3734e+34, 1.1098e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [25]:
# Get a tensor with a certain range (start, end, steps)
arange = torch.arange(4, 10, 3)
arange

tensor([4, 7])

In [28]:
# Get a tensor with equal difference between numbers (start, end, number of values)
linspace = torch.linspace(3, 10, 5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [27]:
# Get a tensor with numbers spaced evenly on a log scale
logspace = torch.logspace(-10, 10, 5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [29]:
# Get a 2d tensor with all zeros but ones on the diagonal
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])