In [1]:
import torch

In [20]:
# Multinomial creates a distribution in relation to the probabilities tensor
# In this example, we define the probability of a value being 0 as 10%, 1 as 80% and 2 as 10%
probabilities = torch.tensor([0.1, 0.8, 0.1])
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([0, 1, 1, 1, 1, 2, 1, 1, 1, 1])


In [24]:
tensor_1 = torch.tensor([1,2,3,4])
tensor_2 = torch.tensor([5])
out = torch.cat((tensor_1, tensor_2), dim=0)
print(out)

tensor([1, 2, 3, 4, 5])


In [29]:
# Tril returns the lower triangle of a matrix.
# This is useful for iteratively taking into account the entirety of a block of data.
ones = torch.ones(5,5)
print(ones)
out = torch.tril(ones)
print(out)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])


In [21]:
# Triu returns the upper triangle of a matrix.
ones = torch.ones(5,5)
print(ones)
out = torch.triu(ones)
print(out)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])


In [13]:
# Exp returns the e^num for each num in the matrix
demo = torch.zeros(5,5).masked_fill(torch.triu(torch.ones(5,5, dtype=torch.bool)), float("-inf"))
print(demo)
exponentiated = torch.exp(demo)
print(exponentiated)

tensor([[-inf, -inf, -inf, -inf, -inf],
        [0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf]])
tensor([[0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.]])


In [18]:
# Transpose switches dimensions of the array
input = torch.zeros(1,2,3)
print(input.transpose(0,2).shape)
print(input.transpose(0,1).shape)

torch.Size([3, 2, 1])
torch.Size([2, 1, 3])


In [20]:
# Stack adds a number of tensors together over another dimension
t_1 = torch.tensor([1, 2, 3])
t_2 = torch.tensor([4, 5, 6])
t_3 = torch.tensor([7, 8, 9])
out = torch.stack([t_1, t_2, t_3])
print(out)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [39]:
# Softmax normalises a vector to a probability distribution. 
input = torch.tensor([1.,2.,3.])
print(torch.softmax(input, dim=0))

tensor([0.0900, 0.2447, 0.6652])


In [38]:
from torch import nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([-8.5609, -6.3337, -3.3237], grad_fn=<SqueezeBackward4>)
