In [1]:
import torch

In [20]:
# Multinomial creates a distribution in relation to the probabilities tensor
# In this example, we define the probability of a value being 0 as 10%, 1 as 80% and 2 as 10%
probabilities = torch.tensor([0.1, 0.8, 0.1])
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([0, 1, 1, 1, 1, 2, 1, 1, 1, 1])


In [24]:
tensor_1 = torch.tensor([1,2,3,4])
tensor_2 = torch.tensor([5])
out = torch.cat((tensor_1, tensor_2), dim=0)
print(out)

tensor([1, 2, 3, 4, 5])


In [29]:
# Tril returns the lower triangle of a matrix.
# This is useful for iteratively taking into account the entirety of a block of data.
ones = torch.ones(5,5)
print(ones)
out = torch.tril(ones)
print(out)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])


In [31]:
# Triu returns the upper triangle of a matrix.
ones = torch.ones(5,5)
print(ones)
out = torch.triu(ones)
print(out)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])
